// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: lex.jflex

package lexer;

import core.Type;
import core.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\247\u0100"+
    "\10\u0500\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\4\2\22\0\1\1\1\3\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\12\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\0\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\42\1\45\1\46\2\42\1\47\1\50\1\51\1\52"+
    "\1\42\1\53\3\42\1\54\1\55\1\56\1\57\1\60"+
    "\1\0\1\61\1\62\1\63\1\64\1\65\1\66\1\67"+
    "\1\70\1\71\2\42\1\72\1\42\1\73\1\74\2\42"+
    "\1\75\1\76\1\77\1\100\1\101\4\42\1\102\1\103"+
    "\1\104\1\105\6\0\1\2\32\0\1\1\u01df\0\1\1"+
    "\177\0\13\1\35\0\2\2\5\0\1\1\57\0\1\1"+
    "\240\0\1\1\377\0\u0100\106";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\1\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\15\30\1\31\1\32\1\33\1\34\1\35\12\30\1\36"+
    "\1\37\1\40\1\41\1\42\1\0\1\43\1\0\1\44"+
    "\1\45\1\46\1\0\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\2\0\1\56\1\57\1\60\1\61\1\62"+
    "\4\30\1\0\1\60\2\30\1\61\1\26\1\63\1\57"+
    "\1\24\1\42\1\30\1\64\1\30\1\65\11\30\1\66"+
    "\1\64\1\67\1\0\1\1\1\70\1\71\1\72\1\45"+
    "\4\30\1\73\1\3\12\30\1\0\1\54\3\30\1\74"+
    "\4\30\1\75\2\30\1\76\5\30\1\77\1\100\1\101"+
    "\3\30\1\102\1\103\10\30\1\104\1\105\1\106\1\107"+
    "\1\30\1\110\1\111";

  private static int [] zzUnpackAction() {
    int [] result = new int[172];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\107\0\216\0\325\0\u011c\0\u011c\0\u0163\0\u01aa"+
    "\0\u01f1\0\u011c\0\u011c\0\u0238\0\u027f\0\u011c\0\u02c6\0\u030d"+
    "\0\u0354\0\u039b\0\u011c\0\u011c\0\u03e2\0\u0429\0\u0470\0\u011c"+
    "\0\u04b7\0\u04fe\0\u0545\0\u058c\0\u05d3\0\u061a\0\u0661\0\u06a8"+
    "\0\u06ef\0\u0736\0\u077d\0\u07c4\0\u080b\0\u011c\0\u011c\0\u011c"+
    "\0\u0852\0\u06a8\0\u0899\0\u08e0\0\u0927\0\u096e\0\u09b5\0\u09fc"+
    "\0\u0a43\0\u0a8a\0\u0ad1\0\u0b18\0\u011c\0\u0b5f\0\u011c\0\u011c"+
    "\0\u011c\0\325\0\u011c\0\u0ba6\0\u011c\0\u011c\0\u011c\0\u0bed"+
    "\0\u011c\0\u011c\0\u011c\0\u011c\0\u011c\0\u0c34\0\u011c\0\u030d"+
    "\0\u0c7b\0\u0cc2\0\u011c\0\u011c\0\u011c\0\u0d09\0\u0d50\0\u0d97"+
    "\0\u0dde\0\u0e25\0\u0e6c\0\u06a8\0\u0eb3\0\u0efa\0\u06a8\0\u06a8"+
    "\0\u06a8\0\u06a8\0\u06a8\0\u06a8\0\u0f41\0\u06a8\0\u0f88\0\u011c"+
    "\0\u0fcf\0\u1016\0\u105d\0\u10a4\0\u10eb\0\u1132\0\u1179\0\u11c0"+
    "\0\u1207\0\u011c\0\u011c\0\u011c\0\u124e\0\u0e6c\0\u011c\0\u011c"+
    "\0\u011c\0\u06a8\0\u1295\0\u12dc\0\u1323\0\u136a\0\u06a8\0\u06a8"+
    "\0\u13b1\0\u13f8\0\u143f\0\u1486\0\u14cd\0\u1514\0\u155b\0\u15a2"+
    "\0\u15e9\0\u1630\0\u1677\0\u1677\0\u16be\0\u1705\0\u174c\0\u1793"+
    "\0\u17da\0\u1821\0\u1868\0\u18af\0\u011c\0\u18f6\0\u193d\0\u06a8"+
    "\0\u1984\0\u19cb\0\u1a12\0\u1a59\0\u1aa0\0\u06a8\0\u011c\0\u011c"+
    "\0\u1ae7\0\u1b2e\0\u1b75\0\u011c\0\u011c\0\u1bbc\0\u1c03\0\u1c4a"+
    "\0\u1c91\0\u1cd8\0\u1d1f\0\u1d66\0\u1dad\0\u06a8\0\u011c\0\u011c"+
    "\0\u011c\0\u1df4\0\u06a8\0\u011c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[172];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\2\2\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\2\40\1\42\1\43\1\44\4\40\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\40\1\53\1\54\1\55"+
    "\1\56\1\57\2\40\1\60\3\40\1\61\1\62\1\63"+
    "\1\40\1\64\1\65\1\66\1\67\1\70\2\0\2\2"+
    "\132\0\1\71\60\0\4\72\1\73\50\72\1\74\31\72"+
    "\135\0\1\75\70\0\1\76\15\0\1\77\60\0\2\100"+
    "\1\0\103\100\27\0\1\101\75\0\1\102\10\0\1\103"+
    "\77\0\1\104\6\0\1\105\102\0\1\106\112\0\1\107"+
    "\100\0\1\110\1\0\1\22\12\0\1\111\27\0\1\111"+
    "\46\0\1\112\1\113\106\0\1\114\106\0\1\115\1\116"+
    "\101\0\1\40\6\0\14\40\1\117\6\40\4\0\22\40"+
    "\27\0\1\40\6\0\16\40\1\120\4\40\4\0\22\40"+
    "\27\0\1\40\6\0\15\40\1\121\5\40\4\0\22\40"+
    "\27\0\1\40\6\0\15\40\1\122\5\40\4\0\22\40"+
    "\22\0\1\123\1\0\1\123\2\0\1\40\6\0\4\40"+
    "\1\124\6\40\1\125\7\40\4\0\22\40\27\0\1\40"+
    "\6\0\15\40\1\126\5\40\4\0\22\40\27\0\1\40"+
    "\6\0\4\40\1\127\13\40\1\130\2\40\4\0\22\40"+
    "\27\0\1\40\6\0\23\40\4\0\22\40\27\0\1\40"+
    "\6\0\5\40\1\131\15\40\4\0\22\40\27\0\1\40"+
    "\6\0\4\40\1\132\13\40\1\133\2\40\4\0\22\40"+
    "\27\0\1\40\6\0\4\40\1\134\10\40\1\135\5\40"+
    "\4\0\22\40\27\0\1\40\6\0\16\40\1\136\4\40"+
    "\4\0\22\40\27\0\1\40\6\0\7\40\1\137\13\40"+
    "\4\0\22\40\33\0\1\140\102\0\1\40\6\0\23\40"+
    "\4\0\14\40\1\141\5\40\27\0\1\40\6\0\23\40"+
    "\4\0\10\40\1\142\11\40\27\0\1\40\6\0\23\40"+
    "\4\0\14\40\1\143\5\40\22\0\1\123\1\0\1\123"+
    "\2\0\1\40\6\0\23\40\4\0\22\40\27\0\1\40"+
    "\6\0\23\40\4\0\1\40\1\144\20\40\27\0\1\40"+
    "\6\0\23\40\4\0\13\40\1\145\6\40\27\0\1\40"+
    "\6\0\23\40\4\0\5\40\1\146\14\40\27\0\1\40"+
    "\6\0\23\40\4\0\17\40\1\147\2\40\27\0\1\40"+
    "\6\0\23\40\4\0\15\40\1\150\4\40\27\0\1\40"+
    "\6\0\23\40\4\0\14\40\1\151\5\40\33\0\1\152"+
    "\54\0\1\153\3\0\2\72\1\0\103\72\12\0\1\154"+
    "\115\0\1\110\1\0\1\106\12\0\1\155\27\0\1\155"+
    "\36\0\1\123\1\0\1\123\2\0\1\156\112\0\1\157"+
    "\106\0\1\160\1\161\101\0\1\40\6\0\3\40\1\162"+
    "\17\40\4\0\22\40\27\0\1\40\6\0\4\40\1\163"+
    "\16\40\4\0\22\40\27\0\1\40\6\0\14\40\1\164"+
    "\6\40\4\0\22\40\27\0\1\40\6\0\23\40\4\0"+
    "\1\165\21\40\27\0\1\156\106\0\1\40\6\0\17\40"+
    "\1\166\3\40\4\0\22\40\27\0\1\40\6\0\16\40"+
    "\1\167\4\40\4\0\22\40\27\0\1\40\6\0\20\40"+
    "\1\170\2\40\4\0\22\40\27\0\1\40\6\0\10\40"+
    "\1\171\12\40\4\0\22\40\27\0\1\40\6\0\23\40"+
    "\4\0\14\40\1\172\5\40\27\0\1\40\6\0\23\40"+
    "\4\0\1\40\1\173\20\40\27\0\1\40\6\0\23\40"+
    "\4\0\20\40\1\174\1\40\27\0\1\40\6\0\23\40"+
    "\4\0\12\40\1\175\7\40\27\0\1\40\6\0\23\40"+
    "\4\0\17\40\1\176\2\40\27\0\1\40\6\0\23\40"+
    "\4\0\17\40\1\177\2\40\27\0\1\40\6\0\23\40"+
    "\4\0\15\40\1\200\4\40\27\0\1\40\6\0\23\40"+
    "\4\0\20\40\1\201\1\40\27\0\1\40\6\0\23\40"+
    "\4\0\11\40\1\202\10\40\22\0\1\203\1\0\1\203"+
    "\2\0\1\204\106\0\1\40\6\0\1\205\22\40\4\0"+
    "\22\40\27\0\1\40\6\0\20\40\1\206\2\40\4\0"+
    "\22\40\27\0\1\40\6\0\22\40\1\207\4\0\22\40"+
    "\27\0\1\40\6\0\4\40\1\210\16\40\4\0\22\40"+
    "\27\0\1\40\6\0\13\40\1\211\7\40\4\0\22\40"+
    "\27\0\1\40\6\0\23\40\4\0\12\40\1\212\7\40"+
    "\27\0\1\40\6\0\23\40\4\0\15\40\1\213\4\40"+
    "\27\0\1\40\6\0\23\40\4\0\2\40\1\214\17\40"+
    "\27\0\1\40\6\0\23\40\4\0\16\40\1\201\3\40"+
    "\6\0\2\215\17\0\1\40\6\0\23\40\4\0\22\40"+
    "\27\0\1\40\6\0\23\40\4\0\20\40\1\216\1\40"+
    "\27\0\1\40\6\0\23\40\4\0\11\40\1\217\10\40"+
    "\27\0\1\40\6\0\23\40\4\0\5\40\1\220\14\40"+
    "\27\0\1\40\6\0\23\40\4\0\4\40\1\221\15\40"+
    "\27\0\1\204\106\0\1\40\6\0\12\40\1\222\10\40"+
    "\4\0\22\40\27\0\1\40\6\0\10\40\1\223\12\40"+
    "\4\0\22\40\27\0\1\40\6\0\7\40\1\224\13\40"+
    "\4\0\22\40\27\0\1\40\6\0\23\40\4\0\1\225"+
    "\21\40\27\0\1\40\6\0\4\40\1\226\16\40\4\0"+
    "\22\40\6\0\2\227\17\0\1\40\6\0\23\40\4\0"+
    "\22\40\6\0\2\230\17\0\1\40\6\0\23\40\4\0"+
    "\22\40\27\0\1\40\6\0\23\40\4\0\12\40\1\231"+
    "\7\40\27\0\1\40\6\0\23\40\4\0\15\40\1\232"+
    "\4\40\27\0\1\40\6\0\23\40\4\0\13\40\1\233"+
    "\6\40\6\0\2\234\17\0\1\40\6\0\23\40\4\0"+
    "\22\40\6\0\2\235\17\0\1\40\6\0\23\40\4\0"+
    "\22\40\27\0\1\40\6\0\14\40\1\236\6\40\4\0"+
    "\22\40\27\0\1\40\6\0\10\40\1\237\12\40\4\0"+
    "\22\40\27\0\1\40\6\0\10\40\1\240\12\40\4\0"+
    "\22\40\27\0\1\40\6\0\23\40\4\0\5\40\1\241"+
    "\14\40\27\0\1\40\6\0\23\40\4\0\13\40\1\242"+
    "\6\40\27\0\1\40\6\0\23\40\4\0\7\40\1\243"+
    "\12\40\27\0\1\40\6\0\21\40\1\244\1\40\4\0"+
    "\22\40\27\0\1\40\6\0\13\40\1\245\7\40\4\0"+
    "\22\40\27\0\1\40\6\0\5\40\1\246\15\40\4\0"+
    "\22\40\6\0\2\247\17\0\1\40\6\0\23\40\4\0"+
    "\22\40\6\0\2\250\17\0\1\40\6\0\23\40\4\0"+
    "\22\40\6\0\2\251\17\0\1\40\6\0\23\40\4\0"+
    "\22\40\27\0\1\40\6\0\4\40\1\252\16\40\4\0"+
    "\22\40\27\0\1\40\6\0\4\40\1\253\16\40\4\0"+
    "\22\40\6\0\2\254\17\0\1\40\6\0\23\40\4\0"+
    "\22\40\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7739];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\1\2\11\3\1\2\11\2\1\1\11\4\1\2\11"+
    "\3\1\1\11\15\1\3\11\14\1\1\11\1\1\3\11"+
    "\1\0\1\11\1\0\3\11\1\0\5\11\1\1\1\11"+
    "\2\0\1\1\3\11\5\1\1\0\14\1\1\11\11\1"+
    "\3\11\1\0\1\1\3\11\21\1\1\0\11\1\1\11"+
    "\11\1\2\11\3\1\2\11\11\1\3\11\2\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[172];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public core.Token next() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Token(Type.INTEGER_LITERAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 74: break;
          case 2:
            { return new Token(Type.WHITE_SPACE, yyline, yycolumn);
            }
            // fall through
          case 75: break;
          case 3:
            { return new Token(Type.NOT, yyline, yycolumn);
            }
            // fall through
          case 76: break;
          case 4:
            { return new Token(Type.DOUBLE_QUOTE, yyline, yycolumn);
            }
            // fall through
          case 77: break;
          case 5:
            { return new Token(Type.HASH_TAG, yyline, yycolumn);
            }
            // fall through
          case 78: break;
          case 6:
            { return new Token(Type.DOLLAR, yyline, yycolumn);
            }
            // fall through
          case 79: break;
          case 7:
            { return new Token(Type.MODULUS, yyline, yycolumn);
            }
            // fall through
          case 80: break;
          case 8:
            { return new Token(Type.B_AND, yyline, yycolumn);
            }
            // fall through
          case 81: break;
          case 9:
            { return new Token(Type.SINGLE_QUOTE, yyline, yycolumn);
            }
            // fall through
          case 82: break;
          case 10:
            { return new Token(Type.OPEN_BRACKET, yyline, yycolumn);
            }
            // fall through
          case 83: break;
          case 11:
            { return new Token(Type.CLOSE_BRACKET, yyline, yycolumn);
            }
            // fall through
          case 84: break;
          case 12:
            { return new Token(Type.MULTIPLY, yyline, yycolumn);
            }
            // fall through
          case 85: break;
          case 13:
            { return new Token(Type.ADD, yyline, yycolumn);
            }
            // fall through
          case 86: break;
          case 14:
            { return new Token(Type.COMMA, yyline, yycolumn);
            }
            // fall through
          case 87: break;
          case 15:
            { return new Token(Type.SUBTRACT, yyline, yycolumn);
            }
            // fall through
          case 88: break;
          case 16:
            { return new Token(Type.DOT, yyline, yycolumn);
            }
            // fall through
          case 89: break;
          case 17:
            { return new Token(Type.DIVIDE, yyline, yycolumn);
            }
            // fall through
          case 90: break;
          case 18:
            { return new Token(Type.COLON, yyline, yycolumn);
            }
            // fall through
          case 91: break;
          case 19:
            { return new Token(Type.SEMI_COLON, yyline, yycolumn);
            }
            // fall through
          case 92: break;
          case 20:
            { return new Token(Type.LESS_THAN, yyline, yycolumn);
            }
            // fall through
          case 93: break;
          case 21:
            { return new Token(Type.EQUAL_TO, yyline, yycolumn);
            }
            // fall through
          case 94: break;
          case 22:
            { return new Token(Type.GREATER_THAN, yyline, yycolumn);
            }
            // fall through
          case 95: break;
          case 23:
            { return new Token(Type.AT, yyline, yycolumn);
            }
            // fall through
          case 96: break;
          case 24:
            { return new Token(Type.ID, yyline, yycolumn, yytext());
            }
            // fall through
          case 97: break;
          case 25:
            { return new Token(Type.OPEN_SQUARE_BRACKET, yyline, yycolumn);
            }
            // fall through
          case 98: break;
          case 26:
            { return new Token(Type.BACKWARD_SLASH, yyline, yycolumn);
            }
            // fall through
          case 99: break;
          case 27:
            { return new Token(Type.CLOSE_SQUARE_BRACKET, yyline, yycolumn);
            }
            // fall through
          case 100: break;
          case 28:
            { return new Token(Type.B_XOR, yyline, yycolumn);
            }
            // fall through
          case 101: break;
          case 29:
            { return new Token(Type.UNDER_SCORE, yyline, yycolumn);
            }
            // fall through
          case 102: break;
          case 30:
            { return new Token(Type.OPEN_CURLY_BRACE, yyline, yycolumn);
            }
            // fall through
          case 103: break;
          case 31:
            { return new Token(Type.B_OR, yyline, yycolumn);
            }
            // fall through
          case 104: break;
          case 32:
            { return new Token(Type.CLOSE_CURLY_BRACE, yyline, yycolumn);
            }
            // fall through
          case 105: break;
          case 33:
            { return new Token(Type.B_NOT, yyline, yycolumn);
            }
            // fall through
          case 106: break;
          case 34:
            { return new Token(Type.NOT_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 107: break;
          case 35:
            { return new Token(Type.STRING_LITERAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 108: break;
          case 36:
            { return new Token(Type.MODULUS_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 109: break;
          case 37:
            { return new Token(Type.AND, yyline, yycolumn);
            }
            // fall through
          case 110: break;
          case 38:
            { return new Token(Type.B_AND_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 111: break;
          case 39:
            { return new Token(Type.PRODUCT_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 112: break;
          case 40:
            { return new Token(Type.INCREMENT, yyline, yycolumn);
            }
            // fall through
          case 113: break;
          case 41:
            { return new Token(Type.ADD_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 114: break;
          case 42:
            { return new Token(Type.DECREMENT, yyline, yycolumn);
            }
            // fall through
          case 115: break;
          case 43:
            { return new Token(Type.SUBTRACT_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 116: break;
          case 44:
            { return new Token(Type.DOUBLE_LITERAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 117: break;
          case 45:
            { return new Token(Type.DIVIDE_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 118: break;
          case 46:
            { return new Token(Type.B_LEFT_SHIFT, yyline, yycolumn);
            }
            // fall through
          case 119: break;
          case 47:
            { return new Token(Type.LESS_THAN_EQUAL, yyline, yycolumn);
            }
            // fall through
          case 120: break;
          case 48:
            { return new Token(Type.EQUALS, yyline, yycolumn);
            }
            // fall through
          case 121: break;
          case 49:
            { return new Token(Type.GREATER_THAN_EQUAL, yyline, yycolumn);
            }
            // fall through
          case 122: break;
          case 50:
            { return new Token(Type.B_RIGHT_SHIFT, yyline, yycolumn);
            }
            // fall through
          case 123: break;
          case 51:
            { return new Token(Type.IF, yyline, yycolumn);
            }
            // fall through
          case 124: break;
          case 52:
            { return new Token(Type.OR, yyline, yycolumn);
            }
            // fall through
          case 125: break;
          case 53:
            { return new Token(Type.B_XOR_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 126: break;
          case 54:
            { return new Token(Type.B_OR_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 127: break;
          case 55:
            { return new Token(Type.CHARACTER_LITERAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 128: break;
          case 56:
            { return new Token(Type.B_LEFT_SHIFT_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 129: break;
          case 57:
            { return new Token(Type.B_RIGHT_SHIFT_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 130: break;
          case 58:
            { return new Token(Type.B_RIGHT_SHIFT_ZERO, yyline, yycolumn);
            }
            // fall through
          case 131: break;
          case 59:
            { return new Token(Type.FOR, yyline, yycolumn);
            }
            // fall through
          case 132: break;
          case 60:
            { return new Token(Type.ELSE, yyline, yycolumn);
            }
            // fall through
          case 133: break;
          case 61:
            { return new Token(Type.INTEGER, yyline, yycolumn);
            }
            // fall through
          case 134: break;
          case 62:
            { return new Token(Type.BOOLEAN_LITERAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 135: break;
          case 63:
            { return new Token(Type.WHILE, yyline, yycolumn);
            }
            // fall through
          case 136: break;
          case 64:
            { return new Token(Type.BOOLEAN, yyline, yycolumn);
            }
            // fall through
          case 137: break;
          case 65:
            { return new Token(Type.CHARACTER, yyline, yycolumn);
            }
            // fall through
          case 138: break;
          case 66:
            { return new Token(Type.VOID, yyline, yycolumn);
            }
            // fall through
          case 139: break;
          case 67:
            { return new Token(Type.BREAK, yyline, yycolumn);
            }
            // fall through
          case 140: break;
          case 68:
            { return new Token(Type.ELSE_IF, yyline, yycolumn);
            }
            // fall through
          case 141: break;
          case 69:
            { return new Token(Type.DOUBLE, yyline, yycolumn);
            }
            // fall through
          case 142: break;
          case 70:
            { return new Token(Type.RETURN, yyline, yycolumn);
            }
            // fall through
          case 143: break;
          case 71:
            { return new Token(Type.STRING, yyline, yycolumn);
            }
            // fall through
          case 144: break;
          case 72:
            { return new Token(Type.DO_WHILE, yyline, yycolumn);
            }
            // fall through
          case 145: break;
          case 73:
            { return new Token(Type.CONTINUE, yyline, yycolumn);
            }
            // fall through
          case 146: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
