// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: lex.jflex

package lexer;

import core.Type;
import core.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\247\u0100"+
    "\10\u0500\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\4\2\22\0\1\1\1\3\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\12\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\0\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\42\1\45\1\46\2\42\1\47\1\50\1\51\1\52"+
    "\1\42\1\53\3\42\1\54\1\55\1\56\1\57\1\60"+
    "\1\0\1\61\1\62\1\63\1\64\1\65\1\66\1\42"+
    "\1\67\1\70\2\42\1\71\1\42\1\72\1\73\2\42"+
    "\1\74\1\75\1\76\1\77\1\100\4\42\1\101\1\102"+
    "\1\103\1\104\6\0\1\2\32\0\1\1\u01df\0\1\1"+
    "\177\0\13\1\35\0\2\2\5\0\1\1\57\0\1\1"+
    "\240\0\1\1\377\0\u0100\105";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\1\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\15\30\1\31\1\32\1\33\1\34\1\35\11\30\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\0\1\47\1\50\1\51\1\52\1\53\1\54\1\55"+
    "\2\0\1\56\1\57\1\60\1\61\1\62\1\63\4\30"+
    "\1\0\1\60\2\30\1\61\1\26\1\64\1\57\1\24"+
    "\1\42\1\30\1\65\1\30\1\66\10\30\1\67\1\65"+
    "\1\70\1\0\1\1\1\71\1\72\1\73\1\45\4\30"+
    "\1\74\1\3\11\30\1\0\1\54\3\30\1\75\4\30"+
    "\1\76\1\30\1\77\5\30\1\100\1\101\1\102\2\30"+
    "\1\103\1\104\7\30\1\105\1\106\1\107\1\30\1\110"+
    "\1\111";

  private static int [] zzUnpackAction() {
    int [] result = new int[164];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\106\0\214\0\322\0\322\0\u0118\0\u015e\0\u01a4"+
    "\0\u01ea\0\322\0\322\0\u0230\0\u0276\0\322\0\u02bc\0\u0302"+
    "\0\u0348\0\u038e\0\322\0\322\0\u03d4\0\u041a\0\u0460\0\u04a6"+
    "\0\u04ec\0\u0532\0\u0578\0\u05be\0\u0604\0\u064a\0\u0690\0\u06d6"+
    "\0\u071c\0\u0762\0\u07a8\0\u07ee\0\u0834\0\322\0\322\0\322"+
    "\0\u087a\0\u06d6\0\u08c0\0\u0906\0\u094c\0\u0992\0\u09d8\0\u0a1e"+
    "\0\u0a64\0\u0aaa\0\u0af0\0\322\0\u0b36\0\322\0\322\0\322"+
    "\0\322\0\322\0\322\0\322\0\u0b7c\0\322\0\322\0\322"+
    "\0\322\0\322\0\u0bc2\0\322\0\u0302\0\u0c08\0\u0c4e\0\322"+
    "\0\322\0\322\0\u0c94\0\322\0\u0cda\0\u0d20\0\u0d66\0\u0dac"+
    "\0\u0df2\0\u06d6\0\u0e38\0\u0e7e\0\u06d6\0\u06d6\0\u06d6\0\u06d6"+
    "\0\u06d6\0\u06d6\0\u0ec4\0\u06d6\0\u0f0a\0\322\0\u0f50\0\u0f96"+
    "\0\u0fdc\0\u1022\0\u1068\0\u10ae\0\u10f4\0\u113a\0\322\0\322"+
    "\0\322\0\u1180\0\u0df2\0\322\0\322\0\322\0\u06d6\0\u11c6"+
    "\0\u120c\0\u1252\0\u1298\0\u06d6\0\u06d6\0\u12de\0\u1324\0\u136a"+
    "\0\u13b0\0\u13f6\0\u143c\0\u1482\0\u14c8\0\u150e\0\u1554\0\u1554"+
    "\0\u159a\0\u15e0\0\u1626\0\u166c\0\u16b2\0\u16f8\0\u173e\0\u1784"+
    "\0\322\0\u17ca\0\u06d6\0\u1810\0\u1856\0\u189c\0\u18e2\0\u1928"+
    "\0\u06d6\0\322\0\322\0\u196e\0\u19b4\0\322\0\322\0\u19fa"+
    "\0\u1a40\0\u1a86\0\u1acc\0\u1b12\0\u1b58\0\u1b9e\0\u06d6\0\322"+
    "\0\322\0\u1be4\0\u06d6\0\322";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[164];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\2\2\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\2\40\1\42\1\43\1\44\4\40\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\40\1\53\1\54\1\55"+
    "\1\56\1\57\1\40\1\60\3\40\1\61\1\40\1\62"+
    "\1\40\1\63\1\64\1\65\1\66\1\67\2\0\2\2"+
    "\131\0\1\70\205\0\1\71\113\0\1\72\67\0\1\73"+
    "\15\0\1\74\57\0\2\75\1\0\102\75\27\0\1\76"+
    "\74\0\1\77\10\0\1\100\76\0\1\101\6\0\1\102"+
    "\101\0\1\103\111\0\1\104\77\0\1\105\1\0\1\22"+
    "\12\0\1\106\27\0\1\106\45\0\1\107\1\110\105\0"+
    "\1\111\105\0\1\112\1\113\76\0\1\114\107\0\1\40"+
    "\6\0\14\40\1\115\6\40\4\0\21\40\27\0\1\40"+
    "\6\0\16\40\1\116\4\40\4\0\21\40\27\0\1\40"+
    "\6\0\15\40\1\117\5\40\4\0\21\40\27\0\1\40"+
    "\6\0\15\40\1\120\5\40\4\0\21\40\22\0\1\121"+
    "\1\0\1\121\2\0\1\40\6\0\4\40\1\122\6\40"+
    "\1\123\7\40\4\0\21\40\27\0\1\40\6\0\15\40"+
    "\1\124\5\40\4\0\21\40\27\0\1\40\6\0\4\40"+
    "\1\125\13\40\1\126\2\40\4\0\21\40\27\0\1\40"+
    "\6\0\23\40\4\0\21\40\27\0\1\40\6\0\5\40"+
    "\1\127\15\40\4\0\21\40\27\0\1\40\6\0\4\40"+
    "\1\130\13\40\1\131\2\40\4\0\21\40\27\0\1\40"+
    "\6\0\4\40\1\132\10\40\1\133\5\40\4\0\21\40"+
    "\27\0\1\40\6\0\16\40\1\134\4\40\4\0\21\40"+
    "\27\0\1\40\6\0\7\40\1\135\13\40\4\0\21\40"+
    "\33\0\1\136\101\0\1\40\6\0\23\40\4\0\13\40"+
    "\1\137\5\40\27\0\1\40\6\0\23\40\4\0\7\40"+
    "\1\140\11\40\27\0\1\40\6\0\23\40\4\0\13\40"+
    "\1\141\5\40\22\0\1\121\1\0\1\121\2\0\1\40"+
    "\6\0\23\40\4\0\21\40\27\0\1\40\6\0\23\40"+
    "\4\0\1\40\1\142\17\40\27\0\1\40\6\0\23\40"+
    "\4\0\12\40\1\143\6\40\27\0\1\40\6\0\23\40"+
    "\4\0\5\40\1\144\13\40\27\0\1\40\6\0\23\40"+
    "\4\0\14\40\1\145\4\40\27\0\1\40\6\0\23\40"+
    "\4\0\13\40\1\146\5\40\33\0\1\147\53\0\1\150"+
    "\14\0\1\151\114\0\1\105\1\0\1\103\12\0\1\152"+
    "\27\0\1\152\35\0\1\121\1\0\1\121\2\0\1\153"+
    "\111\0\1\154\105\0\1\155\1\156\100\0\1\40\6\0"+
    "\3\40\1\157\17\40\4\0\21\40\27\0\1\40\6\0"+
    "\4\40\1\160\16\40\4\0\21\40\27\0\1\40\6\0"+
    "\14\40\1\161\6\40\4\0\21\40\27\0\1\40\6\0"+
    "\23\40\4\0\1\162\20\40\27\0\1\153\105\0\1\40"+
    "\6\0\17\40\1\163\3\40\4\0\21\40\27\0\1\40"+
    "\6\0\16\40\1\164\4\40\4\0\21\40\27\0\1\40"+
    "\6\0\20\40\1\165\2\40\4\0\21\40\27\0\1\40"+
    "\6\0\10\40\1\166\12\40\4\0\21\40\27\0\1\40"+
    "\6\0\23\40\4\0\13\40\1\167\5\40\27\0\1\40"+
    "\6\0\23\40\4\0\1\40\1\170\17\40\27\0\1\40"+
    "\6\0\23\40\4\0\17\40\1\171\1\40\27\0\1\40"+
    "\6\0\23\40\4\0\11\40\1\172\7\40\27\0\1\40"+
    "\6\0\23\40\4\0\16\40\1\173\2\40\27\0\1\40"+
    "\6\0\23\40\4\0\16\40\1\174\2\40\27\0\1\40"+
    "\6\0\23\40\4\0\17\40\1\175\1\40\27\0\1\40"+
    "\6\0\23\40\4\0\10\40\1\176\10\40\22\0\1\177"+
    "\1\0\1\177\2\0\1\200\105\0\1\40\6\0\1\201"+
    "\22\40\4\0\21\40\27\0\1\40\6\0\20\40\1\202"+
    "\2\40\4\0\21\40\27\0\1\40\6\0\22\40\1\203"+
    "\4\0\21\40\27\0\1\40\6\0\4\40\1\204\16\40"+
    "\4\0\21\40\27\0\1\40\6\0\13\40\1\205\7\40"+
    "\4\0\21\40\27\0\1\40\6\0\23\40\4\0\11\40"+
    "\1\206\7\40\27\0\1\40\6\0\23\40\4\0\14\40"+
    "\1\207\4\40\27\0\1\40\6\0\23\40\4\0\2\40"+
    "\1\210\16\40\27\0\1\40\6\0\23\40\4\0\15\40"+
    "\1\175\3\40\6\0\2\211\17\0\1\40\6\0\23\40"+
    "\4\0\21\40\27\0\1\40\6\0\23\40\4\0\17\40"+
    "\1\212\1\40\27\0\1\40\6\0\23\40\4\0\5\40"+
    "\1\213\13\40\27\0\1\40\6\0\23\40\4\0\4\40"+
    "\1\214\14\40\27\0\1\200\105\0\1\40\6\0\12\40"+
    "\1\215\10\40\4\0\21\40\27\0\1\40\6\0\10\40"+
    "\1\216\12\40\4\0\21\40\27\0\1\40\6\0\7\40"+
    "\1\217\13\40\4\0\21\40\27\0\1\40\6\0\23\40"+
    "\4\0\1\220\20\40\27\0\1\40\6\0\4\40\1\221"+
    "\16\40\4\0\21\40\6\0\2\222\17\0\1\40\6\0"+
    "\23\40\4\0\21\40\6\0\2\223\17\0\1\40\6\0"+
    "\23\40\4\0\21\40\27\0\1\40\6\0\23\40\4\0"+
    "\11\40\1\224\7\40\27\0\1\40\6\0\23\40\4\0"+
    "\14\40\1\225\4\40\6\0\2\226\17\0\1\40\6\0"+
    "\23\40\4\0\21\40\6\0\2\227\17\0\1\40\6\0"+
    "\23\40\4\0\21\40\27\0\1\40\6\0\14\40\1\230"+
    "\6\40\4\0\21\40\27\0\1\40\6\0\10\40\1\231"+
    "\12\40\4\0\21\40\27\0\1\40\6\0\10\40\1\232"+
    "\12\40\4\0\21\40\27\0\1\40\6\0\23\40\4\0"+
    "\5\40\1\233\13\40\27\0\1\40\6\0\23\40\4\0"+
    "\12\40\1\234\6\40\27\0\1\40\6\0\21\40\1\235"+
    "\1\40\4\0\21\40\27\0\1\40\6\0\13\40\1\236"+
    "\7\40\4\0\21\40\27\0\1\40\6\0\5\40\1\237"+
    "\15\40\4\0\21\40\6\0\2\240\17\0\1\40\6\0"+
    "\23\40\4\0\21\40\6\0\2\241\17\0\1\40\6\0"+
    "\23\40\4\0\21\40\27\0\1\40\6\0\4\40\1\242"+
    "\16\40\4\0\21\40\27\0\1\40\6\0\4\40\1\243"+
    "\16\40\4\0\21\40\6\0\2\244\17\0\1\40\6\0"+
    "\23\40\4\0\21\40\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7210];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\1\2\11\4\1\2\11\2\1\1\11\4\1\2\11"+
    "\21\1\3\11\13\1\1\11\1\1\7\11\1\0\5\11"+
    "\1\1\1\11\2\0\1\1\3\11\1\1\1\11\4\1"+
    "\1\0\14\1\1\11\10\1\3\11\1\0\1\1\3\11"+
    "\20\1\1\0\11\1\1\11\10\1\2\11\2\1\2\11"+
    "\10\1\2\11\2\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[164];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public core.Token next() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Token(Type.INTEGER_LITERAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 74: break;
          case 2:
            { return new Token(Type.WHITE_SPACE, yyline, yycolumn);
            }
            // fall through
          case 75: break;
          case 3:
            { return new Token(Type.NOT, yyline, yycolumn);
            }
            // fall through
          case 76: break;
          case 4:
            { return new Token(Type.DOUBLE_QUOTE, yyline, yycolumn);
            }
            // fall through
          case 77: break;
          case 5:
            { return new Token(Type.HASH_TAG, yyline, yycolumn);
            }
            // fall through
          case 78: break;
          case 6:
            { return new Token(Type.DOLLAR, yyline, yycolumn);
            }
            // fall through
          case 79: break;
          case 7:
            { return new Token(Type.MODULUS, yyline, yycolumn);
            }
            // fall through
          case 80: break;
          case 8:
            { return new Token(Type.B_AND, yyline, yycolumn);
            }
            // fall through
          case 81: break;
          case 9:
            { return new Token(Type.SINGLE_QUOTE, yyline, yycolumn);
            }
            // fall through
          case 82: break;
          case 10:
            { return new Token(Type.OPEN_BRACKET, yyline, yycolumn);
            }
            // fall through
          case 83: break;
          case 11:
            { return new Token(Type.CLOSE_BRACKET, yyline, yycolumn);
            }
            // fall through
          case 84: break;
          case 12:
            { return new Token(Type.MULTIPLY, yyline, yycolumn);
            }
            // fall through
          case 85: break;
          case 13:
            { return new Token(Type.ADD, yyline, yycolumn);
            }
            // fall through
          case 86: break;
          case 14:
            { return new Token(Type.COMMA, yyline, yycolumn);
            }
            // fall through
          case 87: break;
          case 15:
            { return new Token(Type.SUBTRACT, yyline, yycolumn);
            }
            // fall through
          case 88: break;
          case 16:
            { return new Token(Type.DOT, yyline, yycolumn);
            }
            // fall through
          case 89: break;
          case 17:
            { return new Token(Type.DIVIDE, yyline, yycolumn);
            }
            // fall through
          case 90: break;
          case 18:
            { return new Token(Type.COLON, yyline, yycolumn);
            }
            // fall through
          case 91: break;
          case 19:
            { return new Token(Type.SEMI_COLON, yyline, yycolumn);
            }
            // fall through
          case 92: break;
          case 20:
            { return new Token(Type.LESS_THAN, yyline, yycolumn);
            }
            // fall through
          case 93: break;
          case 21:
            { return new Token(Type.EQUAL_TO, yyline, yycolumn);
            }
            // fall through
          case 94: break;
          case 22:
            { return new Token(Type.GREATER_THAN, yyline, yycolumn);
            }
            // fall through
          case 95: break;
          case 23:
            { return new Token(Type.AT, yyline, yycolumn);
            }
            // fall through
          case 96: break;
          case 24:
            { return new Token(Type.ID, yyline, yycolumn, yytext());
            }
            // fall through
          case 97: break;
          case 25:
            { return new Token(Type.OPEN_SQUARE_BRACKET, yyline, yycolumn);
            }
            // fall through
          case 98: break;
          case 26:
            { return new Token(Type.BACKWARD_SLASH, yyline, yycolumn);
            }
            // fall through
          case 99: break;
          case 27:
            { return new Token(Type.CLOSE_SQUARE_BRACKET, yyline, yycolumn);
            }
            // fall through
          case 100: break;
          case 28:
            { return new Token(Type.B_XOR, yyline, yycolumn);
            }
            // fall through
          case 101: break;
          case 29:
            { return new Token(Type.UNDER_SCORE, yyline, yycolumn);
            }
            // fall through
          case 102: break;
          case 30:
            { return new Token(Type.OPEN_CURLY_BRACE, yyline, yycolumn);
            }
            // fall through
          case 103: break;
          case 31:
            { return new Token(Type.B_OR, yyline, yycolumn);
            }
            // fall through
          case 104: break;
          case 32:
            { return new Token(Type.CLOSE_CURLY_BRACE, yyline, yycolumn);
            }
            // fall through
          case 105: break;
          case 33:
            { return new Token(Type.B_NOT, yyline, yycolumn);
            }
            // fall through
          case 106: break;
          case 34:
            { return new Token(Type.NOT_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 107: break;
          case 35:
            { return new Token(Type.FUNCTION_CALL_PREFIX, yyline, yycolumn);
            }
            // fall through
          case 108: break;
          case 36:
            { return new Token(Type.MODULUS_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 109: break;
          case 37:
            { return new Token(Type.AND, yyline, yycolumn);
            }
            // fall through
          case 110: break;
          case 38:
            { return new Token(Type.B_AND_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 111: break;
          case 39:
            { return new Token(Type.PRODUCT_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 112: break;
          case 40:
            { return new Token(Type.INCREMENT, yyline, yycolumn);
            }
            // fall through
          case 113: break;
          case 41:
            { return new Token(Type.ADD_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 114: break;
          case 42:
            { return new Token(Type.DECREMENT, yyline, yycolumn);
            }
            // fall through
          case 115: break;
          case 43:
            { return new Token(Type.SUBTRACT_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 116: break;
          case 44:
            { return new Token(Type.DOUBLE_LITERAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 117: break;
          case 45:
            { return new Token(Type.DIVIDE_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 118: break;
          case 46:
            { return new Token(Type.B_LEFT_SHIFT, yyline, yycolumn);
            }
            // fall through
          case 119: break;
          case 47:
            { return new Token(Type.LESS_THAN_EQUAL, yyline, yycolumn);
            }
            // fall through
          case 120: break;
          case 48:
            { return new Token(Type.EQUALS, yyline, yycolumn);
            }
            // fall through
          case 121: break;
          case 49:
            { return new Token(Type.GREATER_THAN_EQUAL, yyline, yycolumn);
            }
            // fall through
          case 122: break;
          case 50:
            { return new Token(Type.B_RIGHT_SHIFT, yyline, yycolumn);
            }
            // fall through
          case 123: break;
          case 51:
            { return new Token(Type.INTERNAL_CALL_PREFIX, yyline, yycolumn);
            }
            // fall through
          case 124: break;
          case 52:
            { return new Token(Type.IF, yyline, yycolumn);
            }
            // fall through
          case 125: break;
          case 53:
            { return new Token(Type.OR, yyline, yycolumn);
            }
            // fall through
          case 126: break;
          case 54:
            { return new Token(Type.B_XOR_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 127: break;
          case 55:
            { return new Token(Type.B_OR_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 128: break;
          case 56:
            { return new Token(Type.CHARACTER_LITERAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 129: break;
          case 57:
            { return new Token(Type.B_LEFT_SHIFT_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 130: break;
          case 58:
            { return new Token(Type.B_RIGHT_SHIFT_EQUALS, yyline, yycolumn);
            }
            // fall through
          case 131: break;
          case 59:
            { return new Token(Type.B_RIGHT_SHIFT_ZERO, yyline, yycolumn);
            }
            // fall through
          case 132: break;
          case 60:
            { return new Token(Type.FOR, yyline, yycolumn);
            }
            // fall through
          case 133: break;
          case 61:
            { return new Token(Type.ELSE, yyline, yycolumn);
            }
            // fall through
          case 134: break;
          case 62:
            { return new Token(Type.INTEGER, yyline, yycolumn);
            }
            // fall through
          case 135: break;
          case 63:
            { return new Token(Type.BOOLEAN_LITERAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 136: break;
          case 64:
            { return new Token(Type.WHILE, yyline, yycolumn);
            }
            // fall through
          case 137: break;
          case 65:
            { return new Token(Type.BOOLEAN, yyline, yycolumn);
            }
            // fall through
          case 138: break;
          case 66:
            { return new Token(Type.CHARACTER, yyline, yycolumn);
            }
            // fall through
          case 139: break;
          case 67:
            { return new Token(Type.VOID, yyline, yycolumn);
            }
            // fall through
          case 140: break;
          case 68:
            { return new Token(Type.BREAK, yyline, yycolumn);
            }
            // fall through
          case 141: break;
          case 69:
            { return new Token(Type.ELSE_IF, yyline, yycolumn);
            }
            // fall through
          case 142: break;
          case 70:
            { return new Token(Type.DOUBLE, yyline, yycolumn);
            }
            // fall through
          case 143: break;
          case 71:
            { return new Token(Type.RETURN, yyline, yycolumn);
            }
            // fall through
          case 144: break;
          case 72:
            { return new Token(Type.DO_WHILE, yyline, yycolumn);
            }
            // fall through
          case 145: break;
          case 73:
            { return new Token(Type.CONTINUE, yyline, yycolumn);
            }
            // fall through
          case 146: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
